CREATE TABLE CLIENTE (
    IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(14),
    NOMECLIENTE VARCHAR(100)
);

CREATE TABLE PRODUTO (
    IDPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    VALORPRODUTO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    IDPEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT REFERENCES CLIENTE (IDCLIENTE),
    DATAPEDIDO TIMESTAMP NOT NULL,
    VALORTOTAL NUMERIC(20,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE ITEMPEDIDO (
    IDITEMPEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDPEDIDO INT NOT NULL  REFERENCES PEDIDO (IDPEDIDO),
    IDPRODUTO INT NOT NULL REFERENCES PRODUTO (IDPRODUTO),
    QUANTIDADE INT NOT NULL
);

INSERT INTO CLIENTE (NOMECLIENTE) VALUES ('IGO');
--INSERT INTO PRODUTO (DESCRICAO, VALORPRODUTO) VALUES ('HEINEKEN 600ML', 9.99);
--INSERT INTO PEDIDO (IDCLIENTE, DATAPEDIDO, VALORTOTAL) VALUES (1,'2022-08-23T10:15:30',99.99);
--INSERT INTO ITEMPEDIDO (IDPEDIDO, IDPRODUTO, QUANTIDADE) VALUES (1,1,10);
